# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a68587177e6d015c668f8c427b9228fe6859f142b135a96b8aa1f9533c92b258a755a79abde53ada54c3f7eb674fb885bc08c74ba3e97051c4652824225e3ae5

test:
  secret_key_base: 74732f65b0259223f84841f700911015050323798aa0a88cc81e8b1b1921b4bebf3a6e2a11d49b786c14e2250b3a80637f8c8c38c29829d3cde16cfe6c67518b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
